services:
  db:
    image: postgres:16
    container_name: coffee-postgres
    environment:
      POSTGRES_USER: coffee
      POSTGRES_PASSWORD: coffee
      POSTGRES_DB: coffee_dev
    ports:
      - "5432:5432"
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/add_data:/app/add_data
    restart: always
    networks:
      - coffee-network

  backend:
    build: ./backend
    container_name: coffeeshop_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - coffee-network

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:8000/api/v1
    container_name: coffeeshop_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - coffee-network

networks:
  coffee-network:
    driver: bridge


