services:
  db:
    image: postgres:16
    container_name: coffee-postgres
    environment:
      POSTGRES_USER: coffee
      POSTGRES_PASSWORD: coffee
      POSTGRES_DB: coffee_dev
    ports:
      - "5432:5432"
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/add_data:/app/add_data
    restart: always
    networks:
      - coffeeshop_net

  backend:
    build: ./backend
    container_name: coffeeshop_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - coffeeshop_net

  frontend:
    build: ./frontend
    container_name: coffeeshop_frontend
    depends_on:
      - backend
    networks:
      - coffeeshop_net

  nginx:
    image: nginx:alpine
    container_name: coffeeshop_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
      - ./frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - frontend
      - backend
    networks:
      - coffeeshop_net



networks:
  coffeeshop_net:
    driver: bridge